name: system_trading
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy
    - pandas
    - requests
    - beautifulsoup4
    - lxml
    - sqlalchemy
    - pymysql
    - websockets
    - finance-datareader
    - pandas-datareader
    - selenium
    - matplotlib
    - scikit-learn
    - tqdm
    - openpyxl
